#!/bin/sh

# this line from https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd $SCRIPT_DIR/..

source ./Bazaar/.venv/bin/activate
python3.11 -m unittest